stages:
  - tests
  - master

default:
  image: binkhq/python:3.9

complexity:
  stage: tests
  script:
    - pip install xenon flake8_polyfill
    - xenon --max-average A --max-modules B --max-absolute B .

style:
  stage: tests
  script:
    - pip install flake8 black
    - flake8 && black --line-length 120 --check .

type-check:
  stage: tests
  script:
    - pip install mypy sqlalchemy-stubs types-requests
    - mypy --config-file .mypy.ini .

master:
  stage: master
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="master-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/pyqa-bpl:$CTAG" .
    - docker push "$CI_REGISTRY/pyqa-bpl:$CTAG"
  only:
    - master

